


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cadlx
 */
public class Consultar extends javax.swing.JFrame {
tienda objtienda = new tienda();
    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        this.setTitle("Consulta de Galletas");
        CBOMARCA.addItem(objtienda.marca0);
        CBOMARCA.addItem(objtienda.marca1);
        CBOMARCA.addItem(objtienda.marca2);
        CBOMARCA.addItem(objtienda.marca3);
        CBOMARCA.addItem(objtienda.marca4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBOMARCA = new javax.swing.JComboBox<>();
        LBLPRECIO = new javax.swing.JLabel();
        LBLCONTENIDO = new javax.swing.JLabel();
        LBLPESO = new javax.swing.JLabel();
        LBLSABOR = new javax.swing.JLabel();
        BTNCERRAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        CBOMARCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOMARCAActionPerformed(evt);
            }
        });

        LBLPRECIO.setText("jLabel6");

        LBLCONTENIDO.setText("jLabel6");

        LBLPESO.setText("jLabel6");

        LBLSABOR.setText("jLabel6");

        BTNCERRAR.setText("CERRAR");
        BTNCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCERRARActionPerformed(evt);
            }
        });

        jLabel1.setText("MARCA");

        jLabel2.setText("PRECIO (s/.)");

        jLabel3.setText("CONTENIDO (und.)");

        jLabel4.setText("PESO (gr.)");

        jLabel5.setText("SABOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNCERRAR)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLSABOR)
                    .addComponent(LBLPESO)
                    .addComponent(LBLCONTENIDO)
                    .addComponent(LBLPRECIO)
                    .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LBLPRECIO))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LBLCONTENIDO))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LBLPESO))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LBLSABOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(BTNCERRAR)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBOMARCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOMARCAActionPerformed
        // TODO add your handling code here:
        
                  
                
        if(CBOMARCA.getSelectedItem()== objtienda.marca0)
        {
            LBLPRECIO.setText(Double.toString(objtienda.precio0));
            LBLCONTENIDO.setText(Integer.toString(objtienda.contenido0));
            LBLPESO.setText(Double.toString(objtienda.peso0));
            LBLSABOR.setText(objtienda.sabor0);
        }
        else
        if(CBOMARCA.getSelectedItem()== objtienda.marca1)
        {
            LBLPRECIO.setText(Double.toString(objtienda.precio1));
            LBLCONTENIDO.setText(Integer.toString(objtienda.contenido1));
            LBLPESO.setText(Double.toString(objtienda.peso1));
            LBLSABOR.setText(objtienda.sabor1);
        }
        else
         if(CBOMARCA.getSelectedItem()== objtienda.marca2)   
        {
            LBLPRECIO.setText(Double.toString(objtienda.precio2));
            LBLCONTENIDO.setText(Integer.toString(objtienda.contenido2));
            LBLPESO.setText(Double.toString(objtienda.peso2));
            LBLSABOR.setText(objtienda.sabor2);
        }
        else
         if(CBOMARCA.getSelectedItem()== objtienda.marca3)   
        {
            LBLPRECIO.setText(Double.toString(objtienda.precio3));
            LBLCONTENIDO.setText(Integer.toString(objtienda.contenido3));
            LBLPESO.setText(Double.toString(objtienda.peso3));
            LBLSABOR.setText(objtienda.sabor3);
        }
        else
             {
            LBLPRECIO.setText(Double.toString(objtienda.precio4));
            LBLCONTENIDO.setText(Integer.toString(objtienda.contenido4));
            LBLPESO.setText(Double.toString(objtienda.peso4));
            LBLSABOR.setText(objtienda.sabor4);
        }
             
        
    }//GEN-LAST:event_CBOMARCAActionPerformed

    private void BTNCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRARActionPerformed
        // TODO add your handling code here:
        objtienda.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BTNCERRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCERRAR;
    private javax.swing.JComboBox<String> CBOMARCA;
    private javax.swing.JLabel LBLCONTENIDO;
    private javax.swing.JLabel LBLPESO;
    private javax.swing.JLabel LBLPRECIO;
    private javax.swing.JLabel LBLSABOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
