/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cadlx
 */
public class mod extends javax.swing.JFrame {
    tienda objtienda = new tienda();

    /**
     * Creates new form mod
     */
    public mod() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("MODIFICAR GALLETAS");
        CBOMARCA.addItem(objtienda.marca0);
        CBOMARCA.addItem(objtienda.marca1);
        CBOMARCA.addItem(objtienda.marca2);
        CBOMARCA.addItem(objtienda.marca3);
        CBOMARCA.addItem(objtienda.marca4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CBOMARCA = new javax.swing.JComboBox<>();
        TXTPRECIO = new javax.swing.JTextField();
        TXTCONTENIDO = new javax.swing.JTextField();
        TXTPESO = new javax.swing.JTextField();
        TXTSABOR = new javax.swing.JTextField();
        BTNCERRAR = new javax.swing.JButton();
        BTNGRABAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel4.setText("PESO (gr.)");

        jLabel5.setText("SABOR");

        CBOMARCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOMARCAActionPerformed(evt);
            }
        });

        TXTPRECIO.setColumns(8);
        TXTPRECIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPRECIOActionPerformed(evt);
            }
        });

        TXTCONTENIDO.setColumns(8);

        TXTPESO.setColumns(8);

        TXTSABOR.setColumns(8);

        BTNCERRAR.setText("CERRAR");
        BTNCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCERRARActionPerformed(evt);
            }
        });

        BTNGRABAR.setText("GRABAR");
        BTNGRABAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGRABARActionPerformed(evt);
            }
        });

        jLabel1.setText("MARCA");

        jLabel2.setText("PRECIO (s/.)");

        jLabel3.setText("CONTENIDO (und.)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTSABOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTPESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTCONTENIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTPRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(189, 189, 189))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(BTNCERRAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNGRABAR)
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTPRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTCONTENIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTPESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTSABOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNCERRAR)
                    .addComponent(BTNGRABAR))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBOMARCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOMARCAActionPerformed
        // TODO add your handling code here:
        if(CBOMARCA.getSelectedItem()== objtienda.marca0)
        {
            TXTPRECIO.setText(Double.toString(objtienda.precio0));
            TXTCONTENIDO.setText(Integer.toString(objtienda.contenido0));
            TXTPESO.setText(Double.toString(objtienda.peso0));
            TXTSABOR.setText(objtienda.sabor0);
        }
        else
        if(CBOMARCA.getSelectedItem()== objtienda.marca1)
        {
            TXTPRECIO.setText(Double.toString(objtienda.precio1));
            TXTCONTENIDO.setText(Integer.toString(objtienda.contenido1));
            TXTPESO.setText(Double.toString(objtienda.peso1));
            TXTSABOR.setText(objtienda.sabor1);
        }
        else
         if(CBOMARCA.getSelectedItem()== objtienda.marca2)    
        {
            TXTPRECIO.setText(Double.toString(objtienda.precio2));
            TXTCONTENIDO.setText(Integer.toString(objtienda.contenido2));
            TXTPESO.setText(Double.toString(objtienda.peso2));
            TXTSABOR.setText(objtienda.sabor2);
        }
        if(CBOMARCA.getSelectedItem()== objtienda.marca3)
        {
            TXTPRECIO.setText(Double.toString(objtienda.precio3));
            TXTCONTENIDO.setText(Integer.toString(objtienda.contenido3));
            TXTPESO.setText(Double.toString(objtienda.peso3));
            TXTSABOR.setText(objtienda.sabor3);
        }
        else
            if(CBOMARCA.getSelectedItem()== objtienda.marca4)
        {
            TXTPRECIO.setText(Double.toString(objtienda.precio4));
            TXTCONTENIDO.setText(Integer.toString(objtienda.contenido4));
            TXTPESO.setText(Double.toString(objtienda.peso4));
            TXTSABOR.setText(objtienda.sabor4);
        }
       
    }//GEN-LAST:event_CBOMARCAActionPerformed

    private void TXTPRECIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPRECIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPRECIOActionPerformed

    private void BTNCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRARActionPerformed
        // TODO add your handling code here:
        objtienda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNCERRARActionPerformed

    private void BTNGRABARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGRABARActionPerformed
        // TODO add your handling code here:
        if(CBOMARCA.getSelectedItem()== objtienda.marca0)
        {
            objtienda.precio0=Double.parseDouble(TXTPRECIO.getText());
            objtienda.contenido0=Integer.parseInt(TXTCONTENIDO.getText());
            objtienda.peso0=Double.parseDouble(TXTPESO.getText());
            objtienda.sabor0=TXTSABOR.getText();
        }
        else
        if(CBOMARCA.getSelectedItem()== objtienda.marca1)
        {
            objtienda.precio1=Double.parseDouble(TXTPRECIO.getText());
            objtienda.contenido1=Integer.parseInt(TXTCONTENIDO.getText());
            objtienda.peso1=Double.parseDouble(TXTPESO.getText());
            objtienda.sabor1=TXTSABOR.getText();
        }
        else
        if(CBOMARCA.getSelectedItem()== objtienda.marca2)
        {
            objtienda.precio2=Double.parseDouble(TXTPRECIO.getText());
            objtienda.contenido2=Integer.parseInt(TXTCONTENIDO.getText());
            objtienda.peso2=Double.parseDouble(TXTPESO.getText());
            objtienda.sabor2=TXTSABOR.getText();
        }
        else
             if(CBOMARCA.getSelectedItem()== objtienda.marca3)
        {
            objtienda.precio3=Double.parseDouble(TXTPRECIO.getText());
            objtienda.contenido3=Integer.parseInt(TXTCONTENIDO.getText());
            objtienda.peso3=Double.parseDouble(TXTPESO.getText());
            objtienda.sabor3=TXTSABOR.getText();
        }
        else                 
        {
            objtienda.precio4=Double.parseDouble(TXTPRECIO.getText());
            objtienda.contenido4=Integer.parseInt(TXTCONTENIDO.getText());
            objtienda.peso4=Double.parseDouble(TXTPESO.getText());
            objtienda.sabor4=TXTSABOR.getText();
        }
    }//GEN-LAST:event_BTNGRABARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCERRAR;
    private javax.swing.JButton BTNGRABAR;
    private javax.swing.JComboBox<String> CBOMARCA;
    private javax.swing.JTextField TXTCONTENIDO;
    private javax.swing.JTextField TXTPESO;
    private javax.swing.JTextField TXTPRECIO;
    private javax.swing.JTextField TXTSABOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
