/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cadlx
 */
public class repor extends javax.swing.JFrame {
     tienda objtienda = new tienda();

    /**
     * Creates new form repor
     */
    public repor() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Reporte de ventas");
        CBRP.addItem("Seleccione un tipo de reporte");
        CBRP.addItem(objtienda.repor0);
        CBRP.addItem(objtienda.repor1);
        CBRP.addItem(objtienda.repor2);
        CBRP.addItem(objtienda.repor3);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CBRP = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTREPOR = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo de Reporte");

        CBRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBRPActionPerformed(evt);
            }
        });

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TXTREPOR.setColumns(20);
        TXTREPOR.setRows(5);
        jScrollPane1.setViewportView(TXTREPOR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(CBRP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBRPActionPerformed
        // TODO add your handling code here:
        
        if(CBRP.getSelectedItem()== objtienda.repor0)
        {
        TXTREPOR.append("REPORTE POR MARCA"+"\n\n");
        TXTREPOR.append("MARCA:\t "+objtienda.marca0+"\n");
        TXTREPOR.append("PRECIO POR PAQUETE:\t  "+objtienda.precio0+"\n");
        TXTREPOR.append("PAQUETES VENDIDOS:\t  "+objtienda.cont0+"\n");
        TXTREPOR.append("IMPORTE ACUMULADO:\t  S/ "+objtienda.ventaTM0+"\n\n");
        TXTREPOR.append("MARCA:\t "+objtienda.marca1+"\n");
        TXTREPOR.append("PRECIO POR PAQUETE:\t "+objtienda.precio1+"\n");
        TXTREPOR.append("PAQUETES VENDIDOS:\t "+objtienda.cont1+"\n");
        TXTREPOR.append("IMPORTE ACUMULADO:\t S/ "+objtienda.ventaTM1+"\n\n");
        TXTREPOR.append("MARCA:\t  "+objtienda.marca2+"\n");
        TXTREPOR.append("PRECIO POR PAQUETE:\t  "+objtienda.precio2+"\n");
        TXTREPOR.append("PAQUETES VENDIDOS:\t  "+objtienda.cont2+"\n");
        TXTREPOR.append("IMPORTE ACUMULADO:\t  S/ "+objtienda.ventaTM2+"\n\n");
        TXTREPOR.append("MARCA:\t  "+objtienda.marca3+"\n");
        TXTREPOR.append("PRECIO POR PAQUETE:\t  "+objtienda.precio3+"\n");
        TXTREPOR.append("PAQUETES VENDIDOS:\t  "+objtienda.cont3+"\n");
        TXTREPOR.append("IMPORTE ACUMULADO:\t  S/ "+objtienda.ventaTM3+"\n\n");
        TXTREPOR.append("MARCA:\t  "+objtienda.marca4+"\n");
        TXTREPOR.append("PRECIO POR PAQUETE:\t  "+objtienda.precio4+"\n");
        TXTREPOR.append("PAQUETES VENDIDOS:\t  "+objtienda.cont4+"\n");
        TXTREPOR.append("IMPORTE ACUMULADO:\t  S/ "+objtienda.ventaTM4+"\n\n");
        }
        else 
         if(CBRP.getSelectedItem()== objtienda.repor1)   
        { 
          
            
             for ( int i= 0; i <= 4; i++)
          {
              double N[] = new double[5];
               N[0]= objtienda.cont0;
               N[1]= objtienda.cont1;
               N[2]= objtienda.cont2;
               N[3]= objtienda.cont3;
               N[4]= objtienda.cont4;
              String M[] = new String [5];
              M[0]= objtienda.marca0;
              M[1]= objtienda.marca1;
              M[2]= objtienda.marca2;
              M[3]= objtienda.marca3;
              M[4]= objtienda.marca4;
              
               if (N [i] > objtienda.cantOP)
             {double OP = N[i] - objtienda.cantOP;
              TXTREPOR.append("MARCA:\t "+M[i]+"\n");
             TXTREPOR.append("Cantidad total vendida:\t "+ N[i] + "( " + OP +" ms que la cantidad optima )"  +"\n");}
               
            }
              
          }
        else 
         if(CBRP.getSelectedItem()== objtienda.repor2) 
         {
         
         }
    }//GEN-LAST:event_CBRPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        objtienda.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(repor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(repor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(repor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(repor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new repor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBRP;
    private javax.swing.JTextArea TXTREPOR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
